import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <header>
          {/* <TopNavigation /> // A top navigation bar component which exists in entire website from Aaron*/}
        </header>

        <main>
          {/* Main contents for each page*/}
          {children}
        </main>

        <footer>
          {/* Some useful information for clients, such as contact info*/}
        </footer>
      </body>
    </html>
  );
}
